# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14z4L-jBT_WA8pY5ty9BrnkTnpOhOIhK7
"""

from fastapi import FastAPI, File, UploadFile, Header, HTTPException
from fastapi.responses import FileResponse
import os
import shutil
from moviepy.editor import VideoFileClip
import uuid

app = FastAPI()

# 🔐 Change this to your secure API key
API_KEY = "sahil_mp3_app_2026"

UPLOAD_FOLDER = "uploads"
OUTPUT_FOLDER = "outputs"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(OUTPUT_FOLDER, exist_ok=True)


@app.post("/convert")
async def convert_video(
    file: UploadFile = File(...),
    x_api_key: str = Header(None)
):

    # 🔐 API Key validation
    if x_api_key != API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API Key")

    if not file.filename.endswith(".mp4"):
        raise HTTPException(status_code=400, detail="Only MP4 files allowed")

    unique_id = str(uuid.uuid4())
    video_path = os.path.join(UPLOAD_FOLDER, f"{unique_id}.mp4")

    # Save uploaded video
    with open(video_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    try:
        video = VideoFileClip(video_path)

        # 🎵 Extract original filename (without extension)
        original_name = os.path.splitext(file.filename)[0]

        # Clean filename
        clean_name = original_name.split(" _ ")[0].strip()
        clean_name = clean_name.replace(" ", "_")

        mp3_filename = f"{clean_name}.mp3"
        mp3_path = os.path.join(OUTPUT_FOLDER, mp3_filename)

        # Convert
        video.audio.write_audiofile(mp3_path)
        video.close()

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return FileResponse(
        mp3_path,
        media_type="audio/mpeg",
        filename=mp3_filename
    )

!uvicorn main:app --host 0.0.0.0 --port 10000

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from fastapi import FastAPI, File, UploadFile, Header, HTTPException
# from fastapi.responses import FileResponse
# import os
# import shutil
# from moviepy.editor import VideoFileClip
# import uuid
# 
# app = FastAPI()
# 
# # ❇ Change this to your secure API key
# API_KEY = "sahil_mp3_app_2026"
# 
# UPLOAD_FOLDER = "uploads"
# OUTPUT_FOLDER = "outputs"
# 
# os.makedirs(UPLOAD_FOLDER, exist_ok=True)
# os.makedirs(OUTPUT_FOLDER, exist_ok=True)
# 
# 
# @app.post("/convert")
# async def convert_video(
#     file: UploadFile = File(...),
#     x_api_key: str = Header(None)
# ):
# 
#     # ❇ API Key validation
#     if x_api_key != API_KEY:
#         raise HTTPException(status_code=401, detail="Invalid API Key")
# 
#     if not file.filename.endswith(".mp4"):
#         raise HTTPException(status_code=400, detail="Only MP4 files allowed")
# 
#     unique_id = str(uuid.uuid4())
#     video_path = os.path.join(UPLOAD_FOLDER, f"{unique_id}.mp4")
# 
#     # Save uploaded video
#     with open(video_path, "wb") as buffer:
#         shutil.copyfileobj(file.file, buffer)
# 
#     try:
#         video = VideoFileClip(video_path)
# 
#         # ♫ Extract original filename (without extension)
#         original_name = os.path.splitext(file.filename)[0]
# 
#         # Clean filename
#         clean_name = original_name.split(" _ ")[0].strip()
#         clean_name = clean_name.replace(" ", "_")
# 
#         mp3_filename = f"{clean_name}.mp3"
#         mp3_path = os.path.join(OUTPUT_FOLDER, mp3_filename)
# 
#         # Convert
#         video.audio.write_audiofile(mp3_path)
#         video.close()
# 
#     except Exception as e:
#         raise HTTPException(status_code=500, detail=str(e))
# 
#     return FileResponse(
#         mp3_path,
#         media_type="audio/mpeg",
#         filename=mp3_filename
#     )
